#!/usr/bin/env bash

# Follow however many symlinks are needed to get the true directory and name of this script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
SCRIPT_NAME="$( basename "$SOURCE" )"
PYVENV="${PYVENV:-$HOME/User/Development/Python/.venv}"
VENV="$PYVENV/$SCRIPT_NAME"

#
# Do any setup needed
#
deactivate 2> /dev/null
source "$VENV/bin/activate"

# Path to software entry point
SOFTWARE="$SCRIPT_DIR/src/$SCRIPT_NAME.py"

# Add any default args here
SOFTWARE_ARGS=$@

# Run software, passing all args from this script onwards
$SOFTWARE $SOFTWARE_ARGS
